version: '3.8'

secrets:
  DB_ROOT_PWD:
    file: ./secrets/db_root_pwd.txt
  MYSQL_PWD:
    file: ./secrets/mysql_pwd.txt

configs:
  db_custom_config:
    file: ./config/my.cnf

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  db_data:
  app_data:

services:
  app:
    image: your-app-image:1.0.0  # Use your actual app image
    ports:
      - '80:80'
      - '443:443'
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD_FILE=/run/secrets/MYSQL_PWD
    env_file:
      - app.env
    volumes:
      - app_data:/var/www/html
    networks:
      - frontend
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    read_only: true
    tmpfs:
      - /tmp
    secrets:
      - MYSQL_PWD

  db:
    image: mariadb:10.5
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/DB_ROOT_PWD
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD_FILE=/run/secrets/MYSQL_PWD
    env_file:
      - db.env
    volumes:
      - db_data:/var/lib/mysql
      - db_custom_config:/etc/mysql/conf.d/custom.cnf
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "3"
    secrets:
      - DB_ROOT_PWD
      - MYSQL_PWD

secrets:
  DB_ROOT_PWD:
    file: ./secrets/db_root_pwd.txt
  MYSQL_PWD:
    file: ./secrets/mysql_pwd.txt
